/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.poo.game.gui;

import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import uam.poo.game.elementos.Contenedor;
import uam.poo.game.elementos.Mina;

/**
 *
 * @author santi
 */
public class NewJPanel extends javax.swing.JPanel implements Contenedor
{

    
    public Mina mina;  
    
    public NewJPanel()
    {
        this.setSize(800, 800);
        mina = new Mina(new Rectangle(0, 0, this.getWidth(), this.getHeight()));
        mina.setContenedor(this);
        mina.leerMapa();
        mina.cargarMurcielagos(3);
        initComponents();
    }
    
    public void setMina(Mina mina)
    {
        this.mina = mina;
    }

    @Override
    public void paint(Graphics g)
    {
        mina.draw(g);        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_Q)
            System.exit(0);
        
        mina.keyPressed(evt.getKeyCode());
    }//GEN-LAST:event_formKeyPressed

    @Override
    public void refrescar() 
    {
        this.repaint();        
    }

    @Override
    public Rectangle getDimension()
    {
        return this.getBounds();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
